// ============================================================================
// Mock data for development — replaced by AMP API + Esplora in production
// ============================================================================

import type { Proposal, VoteTally, NexbridgeAsset } from "@/governance/types";

export const MOCK_ASSETS: NexbridgeAsset[] = [
  {
    id: "nAAPL",
    assetId: "ce091c998b83c78bb71a632313ba3760f1763d9cfcffae02258ffa9865a37bd2",
    ticker: "nAAPL",
    name: "Nexbridge Apple Inc.",
    description: "Tokenized exposure to Apple Inc. (AAPL) on the Liquid Network via Blockstream AMP.",
    category: "equity",
    precision: 2,
    totalSupply: 1000000,
    navPerToken: 232.47,
    lastUpdated: "2026-02-16T10:00:00Z",
  },
  {
    id: "nMSFT",
    assetId: "a31c5b77a45ec36d2432c31a81b3124f21073c1e6c5de62bcb5e5cf6e9aabe2d",
    ticker: "nMSFT",
    name: "Nexbridge Microsoft Corp.",
    description: "Tokenized exposure to Microsoft Corp. (MSFT) on the Liquid Network via Blockstream AMP.",
    category: "equity",
    precision: 2,
    totalSupply: 800000,
    navPerToken: 448.55,
    lastUpdated: "2026-02-16T10:00:00Z",
  },
  {
    id: "nTSLA",
    assetId: "b2e15d7c8a4f3e6d9c1b2a5f8e7d4c3b2a1f9e8d7c6b5a4f3e2d1c0b9a8f7e6",
    ticker: "nTSLA",
    name: "Nexbridge Tesla Inc.",
    description: "Tokenized exposure to Tesla Inc. (TSLA) on the Liquid Network via Blockstream AMP.",
    category: "equity",
    precision: 2,
    totalSupply: 500000,
    navPerToken: 354.20,
    lastUpdated: "2026-02-16T10:00:00Z",
  },
  {
    id: "nSPY",
    assetId: "d4f6e8a2c1b3d5f7e9a0b2c4d6f8e1a3b5c7d9e0f2a4b6c8d1e3f5a7b9c0d2e4",
    ticker: "nSPY",
    name: "Nexbridge S&P 500 Index",
    description: "Tokenized exposure to the S&P 500 Index via SPY ETF on the Liquid Network.",
    category: "index",
    precision: 2,
    totalSupply: 2000000,
    navPerToken: 601.30,
    lastUpdated: "2026-02-16T10:00:00Z",
  },
  {
    id: "USTBL",
    assetId: "e5a7b9c1d3f5e7a9b0c2d4f6e8a1b3c5d7f9e0a2b4c6d8f1e3a5b7c9d0e2f4a6",
    ticker: "USTBL",
    name: "Nexbridge US Treasury Bills",
    description: "Regulated tokenized U.S. Treasury Bill exposure on the Liquid Network.",
    category: "treasury",
    precision: 8,
    totalSupply: 30000000,
    navPerToken: 1.0,
    lastUpdated: "2026-02-16T10:00:00Z",
  },
  // ── Platform governance ──────────────────────────────────────────────
  {
    id: "NEXBRIDGE",
    assetId: "nexbridge_platform_governance",
    ticker: "NEXBRIDGE",
    name: "NexBridge Platform",
    description: "Community governance proposals for the NexBridge platform and program.",
    category: "platform",
    precision: 2,
    totalSupply: 0, // voting power derived from total portfolio value
    lastUpdated: "2026-02-18T10:00:00Z",
  },
];

// ---------------------------------------------------------------------------
// Proposals — mix of management (closed/results) and shareholder (active)
// ---------------------------------------------------------------------------

export const MOCK_PROPOSALS: Proposal[] = [
  // ── MANAGEMENT PROPOSALS (closed — show results) ────────────────────────

  {
    id: "prop-001",
    title: "Election of Board of Directors — Annual Meeting 2026",
    description:
      "The Board of Directors recommends the election of the following nominees to serve as directors until the next Annual Meeting:\n\n1. Maria Chen — Independent Director, Chair of Audit Committee\n2. James Nakamoto — Independent Director, Chair of Compensation Committee\n3. Sarah Williams — Independent Director, Chair of Governance Committee\n4. David Park — CEO and Director\n5. Ana Rodriguez — CFO and Director\n\nAll nominees are currently serving on the Board and are standing for re-election. Each nominee has been determined to be independent under applicable listing standards, except for Mr. Park and Ms. Rodriguez, who serve as executive officers.\n\nThe Board recommends a vote FOR all nominees.",
    summary: "Elect five directors to the Board for the 2026 term. Board recommends FOR.",
    category: "board_election",
    resolutionType: "ordinary",
    proposerType: "management",
    instructionEventType: "instruction_vote",
    assetId: "ce091c998b83c78bb71a632313ba3760f1763d9cfcffae02258ffa9865a37bd2",
    assetTicker: "nAAPL",
    assetName: "Nexbridge Apple Inc.",
    proposer: "GA_BOARD_NEXBRIDGE",
    status: "closed",
    options: [
      { id: "opt-for", label: "For All Nominees", description: "Vote FOR all five director nominees" },
      { id: "opt-against", label: "Withhold All", description: "Withhold vote from all nominees" },
      { id: "opt-abstain", label: "Abstain", description: "Abstain from voting" },
    ],
    quorumRequired: 10,
    approvalThreshold: 50,
    startBlock: 2790000,
    endBlock: 2794320,
    startTime: "2026-01-20T00:00:00Z",
    endTime: "2026-01-30T00:00:00Z",
    createdAt: "2026-01-19T18:00:00Z",
    snapshotBlock: 2789999,
    totalVotingPower: 1000000,
    recordDate: "2026-01-19T00:00:00Z",
    meetingType: "annual",
    boardRecommendation: "for",
  },

  {
    id: "prop-002",
    title: "Advisory Vote on Executive Compensation (Say-on-Pay)",
    description:
      "In accordance with governance best practices, the Board is providing shareholders with an advisory (non-binding) vote to approve the compensation of our Named Executive Officers as disclosed in the Compensation Discussion and Analysis section.\n\nKey compensation elements for FY2025:\n- Base salary: Aligned with median of peer group\n- Annual incentive: 120% of target (reflecting strong financial performance)\n- Long-term equity awards: 60% performance-based RSUs, 40% time-based RSUs\n- Total CEO compensation: $2.8M (11% increase vs prior year)\n\nThe Compensation Committee engaged an independent consultant (Meridian Compensation Partners) to benchmark pay levels. The committee believes the compensation program effectively aligns executive interests with shareholder value.\n\nThis vote is advisory and non-binding. The Board recommends a vote FOR.",
    summary: "Advisory vote on Named Executive Officer compensation packages. Non-binding. Board recommends FOR.",
    category: "say_on_pay",
    resolutionType: "advisory",
    proposerType: "management",
    instructionEventType: "instruction_vote",
    assetId: "a31c5b77a45ec36d2432c31a81b3124f21073c1e6c5de62bcb5e5cf6e9aabe2d",
    assetTicker: "nMSFT",
    assetName: "Nexbridge Microsoft Corp.",
    proposer: "GA_BOARD_NEXBRIDGE",
    status: "closed",
    options: [
      { id: "opt-for", label: "For", description: "Approve executive compensation" },
      { id: "opt-against", label: "Against", description: "Disapprove executive compensation" },
      { id: "opt-abstain", label: "Abstain", description: "Abstain from voting" },
    ],
    quorumRequired: 10,
    approvalThreshold: 50,
    startBlock: 2791000,
    endBlock: 2795320,
    startTime: "2026-01-22T00:00:00Z",
    endTime: "2026-02-01T00:00:00Z",
    createdAt: "2026-01-21T14:00:00Z",
    snapshotBlock: 2790999,
    totalVotingPower: 800000,
    recordDate: "2026-01-21T00:00:00Z",
    meetingType: "annual",
    boardRecommendation: "for",
  },

  {
    id: "prop-003",
    title: "Approval of Quarterly Dividend Distribution — Q4 2025",
    description:
      "The Board recommends approval of the Q4 2025 quarterly cash dividend for nTSLA token hodlers, payable in L-BTC to registered AmpId addresses.\n\nDividend Details:\n- Amount per token: $0.00 (Tesla does not currently pay a cash dividend; this proposal establishes the framework for future distributions)\n- This vote authorizes the Board to distribute any future Tesla dividend passthrough to nTSLA hodlers\n- Record date: Liquid block #2,791,999 (snapshot of holdings)\n- Payment method: L-BTC distributed via Blockstream AMP to registered AMP IDs\n\nNote: Tesla Inc. (TSLA) does not currently pay dividends. This proposal establishes Nexbridge's distribution framework so that if Tesla initiates a dividend program, nTSLA hodlers will automatically receive their proportional share.\n\nThe Board recommends a vote FOR.",
    summary: "Establish dividend distribution framework for nTSLA hodlers. Board recommends FOR.",
    category: "dividend_distribution",
    resolutionType: "ordinary",
    proposerType: "management",
    instructionEventType: "election",
    assetId: "b2e15d7c8a4f3e6d9c1b2a5f8e7d4c3b2a1f9e8d7c6b5a4f3e2d1c0b9a8f7e6",
    assetTicker: "nTSLA",
    assetName: "Nexbridge Tesla Inc.",
    proposer: "GA_BOARD_NEXBRIDGE",
    status: "closed",
    options: [
      { id: "opt-for", label: "For", description: "Approve dividend framework" },
      { id: "opt-against", label: "Against", description: "Reject this proposal" },
      { id: "opt-abstain", label: "Abstain", description: "Abstain from voting" },
    ],
    quorumRequired: 10,
    approvalThreshold: 50,
    startBlock: 2790000,
    endBlock: 2794320,
    startTime: "2026-01-25T00:00:00Z",
    endTime: "2026-02-05T00:00:00Z",
    createdAt: "2026-01-24T10:00:00Z",
    snapshotBlock: 2789999,
    totalVotingPower: 500000,
    recordDate: "2026-01-24T00:00:00Z",
    meetingType: "annual",
    boardRecommendation: "for",
  },

  // ── SHAREHOLDER PROPOSALS (active — users can vote) ─────────────────────

  {
    id: "prop-004",
    title: "Request Climate Risk Disclosure in Line with TCFD Framework",
    description:
      "SUBMITTED BY: Hodler GAaef12c89b7 (holding 250 nAAPL tokens)\n\nRESOLVED: That shareholders request the Board to publish an annual climate risk report aligned with the Task Force on Climate-related Financial Disclosures (TCFD) framework, beginning FY2026.\n\nSUPPORTING STATEMENT:\nAs a regulated tokenized equity platform, Nexbridge holds fiduciary responsibility to its token hodlers. Investors increasingly require transparency on climate-related risks affecting portfolio companies.\n\nSpecifically, this proposal requests:\n1. Governance: Describe board oversight of climate risks and opportunities\n2. Strategy: Disclose climate-related risks and their impact on business\n3. Risk Management: Describe how climate risks are identified, assessed, and managed\n4. Metrics & Targets: Disclose Scope 1 & 2 emissions and reduction targets\n\nOver 4,000 organizations globally now report under TCFD. For Nexbridge, this is particularly relevant because the underlying equity exposures (Apple, Microsoft, Tesla, etc.) all publish climate disclosures — yet Nexbridge\u2019s own operational risks are not currently disclosed.\n\nThis is an advisory shareholder proposal. Non-binding.",
    summary: "Request Nexbridge to publish annual TCFD-aligned climate risk report starting FY2026.",
    category: "shareholder_esg",
    resolutionType: "advisory",
    proposerType: "shareholder",
    instructionEventType: "instruction_vote",
    assetId: "ce091c998b83c78bb71a632313ba3760f1763d9cfcffae02258ffa9865a37bd2",
    assetTicker: "nAAPL",
    assetName: "Nexbridge Apple Inc.",
    proposer: "GAaef12c89b7",
    status: "active",
    options: [
      { id: "opt-for", label: "For", description: "Support climate risk disclosure" },
      { id: "opt-against", label: "Against", description: "Oppose this proposal" },
      { id: "opt-abstain", label: "Abstain", description: "Abstain from voting" },
    ],
    quorumRequired: 10,
    approvalThreshold: 50,
    startBlock: 2810000,
    endBlock: 2820000,
    startTime: "2026-02-14T00:00:00Z",
    endTime: "2026-02-24T00:00:00Z",
    createdAt: "2026-02-13T09:00:00Z",
    snapshotBlock: 2809999,
    totalVotingPower: 1000000,
    recordDate: "2026-02-13T00:00:00Z",
    meetingType: "special",
  },

  {
    id: "prop-005",
    title: "Reduce Quorum Threshold for Ordinary Resolutions from 10% to 5%",
    description:
      "SUBMITTED BY: Hodler GA7f3e2d1c0b (holding 150 nMSFT tokens)\n\nRESOLVED: That the shareholders request the Board to reduce the quorum threshold for ordinary resolutions from 10% to 5% of total voting power.\n\nSUPPORTING STATEMENT:\nAnalysis of the past 12 voting rounds shows average participation of 7\u201312% of total voting power. The current 10% quorum threshold has caused 3 routine proposals to fail quorum despite clear majority support among participating voters.\n\nOn-chain governance on the Liquid Network enables verifiable participation tracking. A 5% quorum for ordinary resolutions (while maintaining 25% for special resolutions) would:\n- Prevent routine governance from being blocked by low turnout\n- Align with common quorum standards for tokenized asset governance\n- Still require majority of votes cast for approval\n- Preserve the higher 25% threshold for material corporate actions\n\nThis is an advisory shareholder proposal. The Board takes no position.",
    summary: "Reduce ordinary resolution quorum from 10% to 5% to prevent governance deadlocks.",
    category: "shareholder_governance",
    resolutionType: "advisory",
    proposerType: "shareholder",
    instructionEventType: "instruction_vote",
    assetId: "a31c5b77a45ec36d2432c31a81b3124f21073c1e6c5de62bcb5e5cf6e9aabe2d",
    assetTicker: "nMSFT",
    assetName: "Nexbridge Microsoft Corp.",
    proposer: "GA7f3e2d1c0b",
    status: "active",
    options: [
      { id: "opt-for", label: "For", description: "Support reducing quorum to 5%" },
      { id: "opt-against", label: "Against", description: "Keep current 10% quorum" },
      { id: "opt-abstain", label: "Abstain", description: "Abstain from voting" },
    ],
    quorumRequired: 10,
    approvalThreshold: 50,
    startBlock: 2811000,
    endBlock: 2821000,
    startTime: "2026-02-15T00:00:00Z",
    endTime: "2026-02-25T00:00:00Z",
    createdAt: "2026-02-14T16:00:00Z",
    snapshotBlock: 2810999,
    totalVotingPower: 800000,
    recordDate: "2026-02-14T00:00:00Z",
    meetingType: "special",
  },

  {
    id: "prop-006",
    title: "Require CEO/Chair Separation and Independent Board Chair",
    description:
      "SUBMITTED BY: Hodler GA3d8bc4e1a5 (holding 500 nTSLA tokens)\n\nRESOLVED: That shareholders request the Board to adopt a policy requiring the positions of CEO and Board Chair to be held by separate individuals, with the Chair being an independent director.\n\nSUPPORTING STATEMENT:\nCombining the CEO and Board Chair roles creates a structural conflict of interest. The Board\u2019s primary role is to oversee management \u2014 but when the CEO also chairs the Board, oversight is weakened.\n\nKey governance research supports this separation:\n- ISS (Institutional Shareholder Services) considers CEO/Chair separation a governance best practice\n- Glass Lewis recommends independent board leadership as a default\n- 57% of S&P 500 companies have separated the roles (2025 data)\n\nNexbridge currently combines both roles under CEO David Park. While Mr. Park has demonstrated capable leadership, we believe independent board leadership would:\n- Strengthen board oversight of management decisions\n- Improve accountability to token hodlers\n- Align Nexbridge with institutional governance standards\n- Enhance credibility with traditional finance participants\n\nThis is an advisory shareholder proposal. Non-binding.",
    summary: "Require separation of CEO and Board Chair roles, with an independent Chair.",
    category: "shareholder_governance",
    resolutionType: "advisory",
    proposerType: "shareholder",
    instructionEventType: "instruction_vote",
    assetId: "b2e15d7c8a4f3e6d9c1b2a5f8e7d4c3b2a1f9e8d7c6b5a4f3e2d1c0b9a8f7e6",
    assetTicker: "nTSLA",
    assetName: "Nexbridge Tesla Inc.",
    proposer: "GA3d8bc4e1a5",
    status: "active",
    options: [
      { id: "opt-for", label: "For", description: "Support CEO/Chair separation" },
      { id: "opt-against", label: "Against", description: "Keep current structure" },
      { id: "opt-abstain", label: "Abstain", description: "Abstain from voting" },
    ],
    quorumRequired: 10,
    approvalThreshold: 50,
    startBlock: 2812000,
    endBlock: 2822000,
    startTime: "2026-02-15T12:00:00Z",
    endTime: "2026-02-25T12:00:00Z",
    createdAt: "2026-02-14T20:00:00Z",
    snapshotBlock: 2811999,
    totalVotingPower: 500000,
    recordDate: "2026-02-14T00:00:00Z",
    meetingType: "special",
  },

  {
    id: "prop-007",
    title: "Disclose Lobbying and Political Spending by Nexbridge and Its Agents",
    description:
      "SUBMITTED BY: Hodler GAcf791de4b2 (holding 85 nMSFT tokens)\n\nRESOLVED: That shareholders request Nexbridge to prepare and publish semi-annually a report disclosing:\n\n1. Company policy and procedures governing lobbying, both direct and indirect\n2. Payments by Nexbridge used for lobbying, including direct, indirect, and grassroots\n3. Nexbridge\u2019s membership in and payments to trade associations, industry groups, and coalitions engaged in lobbying activities\n4. Any payments made to organizations that write and endorse model regulatory language\n\nSUPPORTING STATEMENT:\nAs a regulated securities issuer operating at the intersection of traditional finance and digital assets, Nexbridge has a material interest in the regulatory environment. Token hodlers deserve transparency about how the company engages with policymakers.\n\nThe digital asset regulatory landscape is rapidly evolving. Nexbridge\u2019s positions on regulatory frameworks (SEC, CFTC, FinCEN) directly affect token hodler rights, custody arrangements, and tax treatment.\n\nThis is especially important given that Nexbridge operates under multiple jurisdictions and its lobbying positions may not always align with all token hodlers\u2019 interests.\n\nThis is an advisory shareholder proposal. Non-binding.",
    summary: "Require semi-annual disclosure of all lobbying and political spending activities.",
    category: "shareholder_transparency",
    resolutionType: "advisory",
    proposerType: "shareholder",
    instructionEventType: "instruction_vote",
    assetId: "a31c5b77a45ec36d2432c31a81b3124f21073c1e6c5de62bcb5e5cf6e9aabe2d",
    assetTicker: "nMSFT",
    assetName: "Nexbridge Microsoft Corp.",
    proposer: "GAcf791de4b2",
    status: "active",
    options: [
      { id: "opt-for", label: "For", description: "Support lobbying disclosure" },
      { id: "opt-against", label: "Against", description: "Oppose this proposal" },
      { id: "opt-abstain", label: "Abstain", description: "Abstain from voting" },
    ],
    quorumRequired: 10,
    approvalThreshold: 50,
    startBlock: 2813000,
    endBlock: 2823000,
    startTime: "2026-02-16T00:00:00Z",
    endTime: "2026-02-26T00:00:00Z",
    createdAt: "2026-02-15T14:00:00Z",
    snapshotBlock: 2812999,
    totalVotingPower: 800000,
    recordDate: "2026-02-15T00:00:00Z",
    meetingType: "special",
  },

  {
    id: "prop-009",
    title: "Require Shareholder Approval for AI Capital Expenditure Exceeding $10B",
    description:
      "SUBMITTED BY: Hodler GA4b82ef19c3 (holding 1,200 nAAPL tokens)\n\nRESOLVED: That shareholders request the Board to adopt a policy requiring shareholder approval before committing capital expenditures exceeding $10 billion in any single fiscal year toward artificial intelligence infrastructure, including data centers, GPU clusters, AI model training, and related acquisitions.\n\nSUPPORTING STATEMENT:\nBig Tech companies are engaged in an unprecedented AI spending race. In 2025 alone, the top 5 tech companies collectively announced over $300 billion in AI-related capital expenditure — much of it with uncertain return on investment.\n\nApple has signaled plans to significantly increase AI infrastructure spending in 2026–2027 to catch up with competitors in generative AI. While strategic investment in AI is important, the scale of these commitments warrants direct shareholder oversight:\n\n- Microsoft committed $80B to AI data centers in FY2025\n- Meta announced $65B in AI capex for 2025\n- Alphabet pledged $75B for AI infrastructure\n- Amazon allocated $100B+ for AI cloud and custom chips\n- Apple's AI spending remains opaque but is expected to accelerate dramatically\n\nKey concerns:\n1. ROI UNCERTAINTY: No company has demonstrated that massive AI capex translates to proportional revenue growth\n2. CONCENTRATION RISK: Over-investment in a single technology wave creates portfolio risk\n3. SHAREHOLDER DILUTION: Debt-financed AI spending may impair dividends and buybacks\n4. COMPETITIVE DYNAMICS: A spending arms race benefits GPU suppliers (Nvidia) more than the spenders\n\nWe are not opposed to AI investment — we simply request that expenditures above $10B receive explicit shareholder approval, ensuring hodlers have a voice in capital allocation decisions of this magnitude.\n\nThis is an advisory shareholder proposal. Non-binding.",
    summary: "Require hodler approval for AI capital expenditure exceeding $10B per fiscal year to ensure oversight of massive AI spending commitments.",
    category: "shareholder_governance",
    resolutionType: "advisory",
    proposerType: "shareholder",
    instructionEventType: "instruction_vote",
    assetId: "ce091c998b83c78bb71a632313ba3760f1763d9cfcffae02258ffa9865a37bd2",
    assetTicker: "nAAPL",
    assetName: "Nexbridge Apple Inc.",
    proposer: "GA4b82ef19c3",
    status: "active",
    options: [
      { id: "opt-for", label: "For", description: "Require shareholder approval for AI capex >$10B" },
      { id: "opt-against", label: "Against", description: "Trust the Board to allocate AI capital" },
      { id: "opt-abstain", label: "Abstain", description: "Abstain from voting" },
    ],
    quorumRequired: 10,
    approvalThreshold: 50,
    startBlock: 2815000,
    endBlock: 2830000,
    startTime: "2026-02-17T00:00:00Z",
    endTime: "2026-03-03T00:00:00Z",
    createdAt: "2026-02-16T12:00:00Z",
    snapshotBlock: 2814999,
    totalVotingPower: 1000000,
    recordDate: "2026-02-16T00:00:00Z",
    meetingType: "special",
  },

  {
    id: "prop-008",
    title: "Cap CEO Total Compensation at 50x Median Employee Pay",
    description:
      "SUBMITTED BY: Hodler GA9e17bca3d6 (holding 420 nAAPL tokens)\n\nRESOLVED: That shareholders request the Board to adopt a policy capping total CEO compensation at no more than 50 times the median total compensation of all Nexbridge employees.\n\nSUPPORTING STATEMENT:\nExcessive executive compensation misaligns incentives between management and token hodlers. The current CEO-to-median-worker pay ratio at Nexbridge is approximately 78:1, which exceeds peer companies in the fintech sector.\n\nResearch shows that companies with moderate CEO pay ratios tend to:\n- Have better long-term stock performance\n- Experience lower executive turnover\n- Maintain higher employee morale and productivity\n- Face fewer governance-related controversies\n\nA 50:1 cap would still allow substantial executive compensation while demonstrating commitment to fair pay practices. For context, the CEO\u2019s current total compensation of $2.8M would be reduced to approximately $1.8M under a 50x cap (based on median employee pay of ~$36,000).\n\nWe note that SEC Dodd-Frank pay ratio rules already require disclosure \u2014 this proposal simply asks the Board to act on that data.\n\nThis is an advisory shareholder proposal. Non-binding.",
    summary: "Cap CEO total compensation at 50 times the median employee pay ratio.",
    category: "shareholder_exec_comp",
    resolutionType: "advisory",
    proposerType: "shareholder",
    instructionEventType: "instruction_vote",
    assetId: "ce091c998b83c78bb71a632313ba3760f1763d9cfcffae02258ffa9865a37bd2",
    assetTicker: "nAAPL",
    assetName: "Nexbridge Apple Inc.",
    proposer: "GA9e17bca3d6",
    status: "active",
    options: [
      { id: "opt-for", label: "For", description: "Support CEO pay cap" },
      { id: "opt-against", label: "Against", description: "Oppose this proposal" },
      { id: "opt-abstain", label: "Abstain", description: "Abstain from voting" },
    ],
    quorumRequired: 10,
    approvalThreshold: 50,
    startBlock: 2814000,
    endBlock: 2824000,
    startTime: "2026-02-16T06:00:00Z",
    endTime: "2026-02-26T06:00:00Z",
    createdAt: "2026-02-15T18:00:00Z",
    snapshotBlock: 2813999,
    totalVotingPower: 1000000,
    recordDate: "2026-02-15T00:00:00Z",
    meetingType: "special",
  },

  // ── NEXBRIDGE COMMUNITY PROPOSALS ──────────────────────────────────────

  {
    id: "community-001",
    title: "Request Tokenization of Nvidia (NVDA)",
    description:
      "SUBMITTED BY: Community member AMP7f3a91bc04\n\nPROPOSAL: The NexBridge community requests that NexBridge add tokenized exposure to Nvidia Corp. (NVDA) as a new NexTR instrument (nNVDA).\n\nRATIONALE:\nNvidia is the world's most valuable semiconductor company with a market capitalization exceeding $3 trillion. Its dominant position in AI accelerators (H100/H200/B200 GPUs) makes it one of the most sought-after equity exposures globally. The current NexTR lineup lacks exposure to the semiconductor sector entirely.\n\nDemand signals:\n- Multiple community members have requested NVDA exposure in Discord\n- NVDA is the 3rd most traded stock globally by dollar volume\n- AI infrastructure spending is projected to exceed $500B annually by 2027\n- Adding nNVDA would complement existing tech exposure (nAAPL, nMSFT, nTSLA)\n\nNexBridge has the existing infrastructure to issue a new NexTR series — the Depositary SPV, custody, and AMP issuance pipeline are already proven with 5 instruments.\n\nThis is an advisory community proposal. Non-binding but expresses community demand.",
    summary: "Add nNVDA (Nvidia) tokenized exposure to the NexBridge platform. The most requested new underlying by the community.",
    category: "community_new_underlying",
    resolutionType: "advisory",
    proposerType: "community",
    instructionEventType: "instruction_vote",
    assetId: "nexbridge_platform_governance",
    assetTicker: "NEXBRIDGE",
    assetName: "NexBridge Platform",
    proposer: "AMP7f3a91bc04",
    status: "active",
    options: [
      { id: "opt-for", label: "For", description: "Support adding nNVDA to the platform" },
      { id: "opt-against", label: "Against", description: "Do not prioritize nNVDA at this time" },
      { id: "opt-abstain", label: "Abstain", description: "Abstain from voting" },
    ],
    quorumRequired: 10,
    approvalThreshold: 50,
    startBlock: 2815000,
    endBlock: 2829320,
    startTime: "2026-02-17T12:00:00Z",
    endTime: "2026-03-03T12:00:00Z",
    createdAt: "2026-02-17T10:00:00Z",
    snapshotBlock: 2814999,
    totalVotingPower: 500000,
    recordDate: "2026-02-17T00:00:00Z",
    meetingType: "special",
  },

  {
    id: "community-002",
    title: "List nAAPL on Bitfinex Securities",
    description:
      "SUBMITTED BY: Community member AMP2d8e44af19\n\nPROPOSAL: The NexBridge community requests that NexBridge pursue listing nAAPL (and subsequently other NexTR instruments) on Bitfinex Securities, the regulated securities trading venue operated by BFXWW Inc.\n\nRATIONALE:\nBitfinex Securities already supports tokenized securities on the Liquid Network and has the regulatory framework for trading Transfer Restricted Assets. Listing nAAPL on Bitfinex Securities would:\n\n- Provide secondary market liquidity for NexTR hodlers\n- Enable price discovery in a regulated venue\n- Attract new participants who already have Bitfinex Securities accounts\n- Demonstrate institutional-grade market structure for tokenized equities\n\nBitfinex Securities has previously listed other Liquid-based tokenized securities, making the technical integration straightforward. The primary work is legal/compliance coordination between NexBridge and Bitfinex Securities.\n\nThis is an advisory community proposal. Non-binding.",
    summary: "List nAAPL on Bitfinex Securities for secondary market trading. First step toward venue-listed NexTR instruments.",
    category: "community_listing_venue",
    resolutionType: "advisory",
    proposerType: "community",
    instructionEventType: "instruction_vote",
    assetId: "nexbridge_platform_governance",
    assetTicker: "NEXBRIDGE",
    assetName: "NexBridge Platform",
    proposer: "AMP2d8e44af19",
    status: "active",
    options: [
      { id: "opt-for", label: "For", description: "Support listing on Bitfinex Securities" },
      { id: "opt-against", label: "Against", description: "Do not prioritize venue listing" },
      { id: "opt-abstain", label: "Abstain", description: "Abstain from voting" },
    ],
    quorumRequired: 10,
    approvalThreshold: 50,
    startBlock: 2815500,
    endBlock: 2829820,
    startTime: "2026-02-17T20:00:00Z",
    endTime: "2026-03-03T20:00:00Z",
    createdAt: "2026-02-17T18:00:00Z",
    snapshotBlock: 2815499,
    totalVotingPower: 500000,
    recordDate: "2026-02-17T00:00:00Z",
    meetingType: "special",
  },

  {
    id: "community-003",
    title: "Add Portfolio Analytics Dashboard to NexTR Portal",
    description:
      "SUBMITTED BY: Community member AMP5c1d73ea88\n\nPROPOSAL: The community requests that NexBridge add a portfolio analytics dashboard to the NexTR portal, providing hodlers with real-time visibility into their positions, P&L, and corporate action history.\n\nREQUESTED FEATURES:\n1. Portfolio overview with current holdings, NAV per token, and total portfolio value\n2. Historical P&L chart (daily/weekly/monthly) per instrument\n3. Corporate action timeline showing past and upcoming events\n4. Distribution history (dividends received, elections made)\n5. Instruction history with on-chain transaction links\n6. Export to CSV/PDF for tax reporting\n\nRATIONALE:\nCurrently, hodlers must manually track their positions and corporate action outcomes. A built-in analytics dashboard would improve the hodler experience significantly and differentiate NexTR from competing tokenized equity platforms.\n\nThis could leverage existing data: AMP API for balances, Esplora for transactions, and the governance backend for instruction history.\n\nThis is an advisory community proposal. Non-binding.",
    summary: "Build a portfolio analytics dashboard with P&L tracking, corporate action history, and export functionality.",
    category: "community_program_features",
    resolutionType: "advisory",
    proposerType: "community",
    instructionEventType: "instruction_vote",
    assetId: "nexbridge_platform_governance",
    assetTicker: "NEXBRIDGE",
    assetName: "NexBridge Platform",
    proposer: "AMP5c1d73ea88",
    status: "active",
    options: [
      { id: "opt-for", label: "For", description: "Support building portfolio analytics" },
      { id: "opt-against", label: "Against", description: "Not a priority right now" },
      { id: "opt-abstain", label: "Abstain", description: "Abstain from voting" },
    ],
    quorumRequired: 10,
    approvalThreshold: 50,
    startBlock: 2816000,
    endBlock: 2830320,
    startTime: "2026-02-18T04:00:00Z",
    endTime: "2026-03-04T04:00:00Z",
    createdAt: "2026-02-18T02:00:00Z",
    snapshotBlock: 2815999,
    totalVotingPower: 500000,
    recordDate: "2026-02-18T00:00:00Z",
    meetingType: "special",
  },

  {
    id: "community-004",
    title: "Publish Monthly Proof-of-Reserves Report",
    description:
      "SUBMITTED BY: Community member AMP8b4f2ce1d7\n\nPROPOSAL: The community requests that NexBridge publish a monthly Proof-of-Reserves (PoR) report for all NexTR instruments, independently verifiable and publicly accessible.\n\nREPORT SHOULD INCLUDE:\n1. Total tokens outstanding per instrument (on-chain, verifiable via AMP)\n2. Corresponding underlying securities held by the Depositary SPV\n3. Custody account statements from the broker/custodian\n4. NAV reconciliation (token supply \u00d7 NAV vs custody value)\n5. Trust/Trustee attestation letter\n6. Methodology notes and auditor information\n\nRATIONALE:\nProof-of-Reserves is the gold standard for transparency in tokenized assets. Monthly publication would:\n- Build trust with existing and prospective hodlers\n- Set an industry standard for tokenized equity transparency\n- Provide data for third-party analytics and research\n- Align with Blockstream\u2019s broader PoR initiatives for Liquid assets\n\nNexBridge already has the data \u2014 this proposal simply requests making it public on a regular cadence.\n\nThis is an advisory community proposal. Non-binding.",
    summary: "Publish monthly Proof-of-Reserves reports for all NexTR instruments with independent verification.",
    category: "community_transparency",
    resolutionType: "advisory",
    proposerType: "community",
    instructionEventType: "instruction_vote",
    assetId: "nexbridge_platform_governance",
    assetTicker: "NEXBRIDGE",
    assetName: "NexBridge Platform",
    proposer: "AMP8b4f2ce1d7",
    status: "closed",
    options: [
      { id: "opt-for", label: "For", description: "Support monthly PoR publication" },
      { id: "opt-against", label: "Against", description: "Oppose this requirement" },
      { id: "opt-abstain", label: "Abstain", description: "Abstain from voting" },
    ],
    quorumRequired: 10,
    approvalThreshold: 50,
    startBlock: 2800000,
    endBlock: 2814320,
    startTime: "2026-02-07T00:00:00Z",
    endTime: "2026-02-17T00:00:00Z",
    createdAt: "2026-02-06T20:00:00Z",
    snapshotBlock: 2799999,
    totalVotingPower: 500000,
    recordDate: "2026-02-06T00:00:00Z",
    meetingType: "special",
  },
];

// ---------------------------------------------------------------------------
// Vote Tallies — realistic voting patterns
// ---------------------------------------------------------------------------

export const MOCK_TALLIES: Record<string, VoteTally> = {
  // Board Election — passed with strong support (closed)
  "prop-001": {
    proposalId: "prop-001",
    options: [
      { optionId: "opt-for", label: "For All Nominees", votes: 342, votingPower: 456000, percentage: 72.3 },
      { optionId: "opt-against", label: "Withhold All", votes: 89, votingPower: 125000, percentage: 19.8 },
      { optionId: "opt-abstain", label: "Abstain", votes: 45, votingPower: 50000, percentage: 7.9 },
    ],
    totalVotes: 476,
    totalVotingPower: 631000,
    quorumReached: true,
    quorumPercentage: 63.1,
    participationRate: 63.1,
  },

  // Say-on-Pay — passed narrowly, some dissent (closed)
  "prop-002": {
    proposalId: "prop-002",
    options: [
      { optionId: "opt-for", label: "For", votes: 198, votingPower: 312000, percentage: 58.2 },
      { optionId: "opt-against", label: "Against", votes: 156, votingPower: 198000, percentage: 36.9 },
      { optionId: "opt-abstain", label: "Abstain", votes: 22, votingPower: 26000, percentage: 4.9 },
    ],
    totalVotes: 376,
    totalVotingPower: 536000,
    quorumReached: true,
    quorumPercentage: 67.0,
    participationRate: 67.0,
  },

  // nTSLA dividend framework — passed easily (closed)
  "prop-003": {
    proposalId: "prop-003",
    options: [
      { optionId: "opt-for", label: "For", votes: 215, votingPower: 285000, percentage: 78.4 },
      { optionId: "opt-against", label: "Against", votes: 42, votingPower: 55000, percentage: 15.1 },
      { optionId: "opt-abstain", label: "Abstain", votes: 18, votingPower: 23500, percentage: 6.5 },
    ],
    totalVotes: 275,
    totalVotingPower: 363500,
    quorumReached: true,
    quorumPercentage: 72.7,
    participationRate: 72.7,
  },

  // Climate disclosure — active, early votes trending in favor
  "prop-004": {
    proposalId: "prop-004",
    options: [
      { optionId: "opt-for", label: "For", votes: 67, votingPower: 98000, percentage: 61.3 },
      { optionId: "opt-against", label: "Against", votes: 28, votingPower: 45000, percentage: 28.1 },
      { optionId: "opt-abstain", label: "Abstain", votes: 9, votingPower: 17000, percentage: 10.6 },
    ],
    totalVotes: 104,
    totalVotingPower: 160000,
    quorumReached: true,
    quorumPercentage: 16.0,
    participationRate: 16.0,
  },

  // Quorum reduction — active, close race
  "prop-005": {
    proposalId: "prop-005",
    options: [
      { optionId: "opt-for", label: "For", votes: 42, votingPower: 38000, percentage: 44.7 },
      { optionId: "opt-against", label: "Against", votes: 39, votingPower: 40000, percentage: 47.1 },
      { optionId: "opt-abstain", label: "Abstain", votes: 8, votingPower: 7000, percentage: 8.2 },
    ],
    totalVotes: 89,
    totalVotingPower: 85000,
    quorumReached: true,
    quorumPercentage: 10.6,
    participationRate: 10.6,
  },

  // CEO/Chair separation — active, quorum not yet reached
  "prop-006": {
    proposalId: "prop-006",
    options: [
      { optionId: "opt-for", label: "For", votes: 35, votingPower: 22000, percentage: 55.0 },
      { optionId: "opt-against", label: "Against", votes: 18, votingPower: 15000, percentage: 37.5 },
      { optionId: "opt-abstain", label: "Abstain", votes: 5, votingPower: 3000, percentage: 7.5 },
    ],
    totalVotes: 58,
    totalVotingPower: 40000,
    quorumReached: false,
    quorumPercentage: 8.0,
    participationRate: 8.0,
  },

  // Lobbying disclosure — active, just started
  "prop-007": {
    proposalId: "prop-007",
    options: [
      { optionId: "opt-for", label: "For", votes: 12, votingPower: 8500, percentage: 53.1 },
      { optionId: "opt-against", label: "Against", votes: 7, votingPower: 5500, percentage: 34.4 },
      { optionId: "opt-abstain", label: "Abstain", votes: 3, votingPower: 2000, percentage: 12.5 },
    ],
    totalVotes: 22,
    totalVotingPower: 16000,
    quorumReached: false,
    quorumPercentage: 2.0,
    participationRate: 2.0,
  },

  // AI capex oversight — active, fresh proposal, strong early support
  "prop-009": {
    proposalId: "prop-009",
    options: [
      { optionId: "opt-for", label: "For", votes: 23, votingPower: 31000, percentage: 62.0 },
      { optionId: "opt-against", label: "Against", votes: 11, votingPower: 15000, percentage: 30.0 },
      { optionId: "opt-abstain", label: "Abstain", votes: 4, votingPower: 4000, percentage: 8.0 },
    ],
    totalVotes: 38,
    totalVotingPower: 50000,
    quorumReached: false,
    quorumPercentage: 5.0,
    participationRate: 5.0,
  },

  // CEO pay cap — active, management/large holders opposing
  "prop-008": {
    proposalId: "prop-008",
    options: [
      { optionId: "opt-for", label: "For", votes: 55, votingPower: 42000, percentage: 38.2 },
      { optionId: "opt-against", label: "Against", votes: 72, votingPower: 58000, percentage: 52.7 },
      { optionId: "opt-abstain", label: "Abstain", votes: 11, votingPower: 10000, percentage: 9.1 },
    ],
    totalVotes: 138,
    totalVotingPower: 110000,
    quorumReached: true,
    quorumPercentage: 11.0,
    participationRate: 11.0,
  },

  // ── NEXBRIDGE COMMUNITY TALLIES ──────────────────────────────────────

  // nNVDA request — active, very strong community support
  "community-001": {
    proposalId: "community-001",
    options: [
      { optionId: "opt-for", label: "For", votes: 89, votingPower: 285000, percentage: 82.4 },
      { optionId: "opt-against", label: "Against", votes: 12, votingPower: 42000, percentage: 12.2 },
      { optionId: "opt-abstain", label: "Abstain", votes: 7, votingPower: 19000, percentage: 5.4 },
    ],
    totalVotes: 108,
    totalVotingPower: 346000,
    quorumReached: false,
    quorumPercentage: 6.9,
    participationRate: 6.9,
  },

  // Bitfinex Securities listing — active, moderate support
  "community-002": {
    proposalId: "community-002",
    options: [
      { optionId: "opt-for", label: "For", votes: 52, votingPower: 178000, percentage: 68.3 },
      { optionId: "opt-against", label: "Against", votes: 18, votingPower: 62000, percentage: 23.8 },
      { optionId: "opt-abstain", label: "Abstain", votes: 8, votingPower: 20600, percentage: 7.9 },
    ],
    totalVotes: 78,
    totalVotingPower: 260600,
    quorumReached: false,
    quorumPercentage: 5.2,
    participationRate: 5.2,
  },

  // Portfolio analytics — active, early voting
  "community-003": {
    proposalId: "community-003",
    options: [
      { optionId: "opt-for", label: "For", votes: 31, votingPower: 98000, percentage: 74.2 },
      { optionId: "opt-against", label: "Against", votes: 6, votingPower: 22000, percentage: 16.7 },
      { optionId: "opt-abstain", label: "Abstain", votes: 4, votingPower: 12000, percentage: 9.1 },
    ],
    totalVotes: 41,
    totalVotingPower: 132000,
    quorumReached: false,
    quorumPercentage: 2.6,
    participationRate: 2.6,
  },

  // Proof-of-Reserves — closed, passed with strong support
  "community-004": {
    proposalId: "community-004",
    options: [
      { optionId: "opt-for", label: "For", votes: 215, votingPower: 892000, percentage: 87.3 },
      { optionId: "opt-against", label: "Against", votes: 24, votingPower: 98000, percentage: 9.6 },
      { optionId: "opt-abstain", label: "Abstain", votes: 10, votingPower: 32000, percentage: 3.1 },
    ],
    totalVotes: 249,
    totalVotingPower: 1022000,
    quorumReached: true,
    quorumPercentage: 20.4,
    participationRate: 20.4,
  },
};
